@Library('devops-shared-library@main') _

pipeline {
    agent any
    
    environment {
        IMAGE_NAME = "chanserey/spring-demo-app"
        IMAGE_TAG = "v1.0.${env.BUILD_NUMBER}"
        CONTAINER_NAME = "spring-demo-prod"
        CONTAINER_PORT = "8080"
        
        TELEGRAM_TOKEN = credentials('telegram-bot-token')
        TELEGRAM_CHAT_ID = credentials('telegram-chat-id')
    }
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/ChansereyGit/spring-demo-app.git'
                sendTelegram("🚀 Spring Boot build started", "${TELEGRAM_TOKEN}", "${TELEGRAM_CHAT_ID}")
            }
        }
        
        stage('Test') {
            steps {
                script {
                    sh './gradlew test'
                }
            }
        }
        
        stage('Build JAR') {
            steps {
                script {
                    sh './gradlew clean build -x test'
                }
            }
        }
        
        stage('Build Image') {
            steps {
                script {
                    buildDockerImage.spring("${IMAGE_NAME}", "${IMAGE_TAG}")
                }
            }
        }
        
        stage('Push Image') {
            steps {
                script {
                    pushDockerImage("${IMAGE_NAME}:${IMAGE_TAG}", "dockerhub-credentials")
                }
            }
        }
        
        stage('Deploy') {
            steps {
                script {
                    deployContainer.spring("${IMAGE_NAME}:${IMAGE_TAG}", "${CONTAINER_NAME}", "${CONTAINER_PORT}")
                }
            }
        }
    }
    
    post {
        success {
            script {
                sendTelegram.buildNotification("SUCCESS", "${TELEGRAM_TOKEN}", "${TELEGRAM_CHAT_ID}")
            }
        }
        failure {
            script {
                sendTelegram.buildNotification("FAILURE", "${TELEGRAM_TOKEN}", "${TELEGRAM_CHAT_ID}")
            }
        }
    }
}
