@Library('devops-shared-library@main') _

pipeline {
    agent any
    
    environment{
        TAG="v1.0.${env.BUILD_NUMBER}"
        IMG_NAME="spring-demo-app"
        DH_USER="chanserey"
        FULL_IMG="${DH_USER}/${IMG_NAME}:${TAG}"
        CHAT_ID=credentials('telegram-chat-id')
        TOKEN=credentials('telegram-bot-token')
    }
    
    stages {
        stage("Checkout"){
            steps{
                git 'https://github.com/ChansereyGit/spring-demo-app.git'
            }
        }
        
        stage('Build'){
            steps{
                script{
                    buildDockerImage("${FULL_IMG}", "${TAG}", "spring")
                }
            }
        }
        
        stage("Push"){
            steps{
                script{
                    pushDockerImage("${DH_USER}/${IMG_NAME}", "${TAG}", "dockerhub-credentials")
                }
            }
        }
        
        stage("Deploy"){
            steps{
                script{
                    sh """
                        docker stop spring-app || true
                        docker rm spring-app || true
                        docker run -dp 8080:8080 --name spring-app ${FULL_IMG}
                    """
                }
            }
        }
    }
    
    post {
        success {
            script {
                sendTelegram("Build Success: ${env.JOB_NAME}","${TOKEN}","${CHAT_ID}")
            }
        }
        failure {
            script {
                sendTelegram("Build Failed: ${env.JOB_NAME}","${TOKEN}","${CHAT_ID}")
            }
        }
    }
}
